// Generated by CoffeeScript 1.8.0
(function() {
  var flavaApp, _game, _gameId;

  flavaApp = angular.module('flavaApp', ['ngRoute', 'ngAnimate', 'ngSanitize']);

  _gameId = 0;

  _game = null;

  flavaApp.config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'splash.html'
    }).when('/select', {
      templateUrl: 'select.html'
    }).when('/game/:id', {
      controller: 'GameCtrl',
      templateUrl: 'game.html'
    }).otherwise({
      redirectTo: '/'
    });
  });

  flavaApp.controller('SplashCtrl', function($scope) {
    var agent;
    agent = navigator.userAgent;
    if (agent.search(/(iPhone|iPod|Android|Mobile)/) !== -1) {
      return $scope.isMobile = true;
    } else {
      return $scope.isMobile = false;
    }
  });

  flavaApp.controller('GameCtrl', function($scope, $routeParams) {
    var _endCallback, _loadCallback;
    $scope.end = false;
    $scope.loaded = false;
    _loadCallback = function() {
      console.log("load complete");
      return $scope.$apply(function() {
        return $scope.loaded = true;
      });
    };
    _endCallback = function(score) {
      console.log("end!!! " + score);
      return $scope.$apply(function() {
        $scope.end = true;
        $scope.score = score;
        if (score > 97500) {
          $scope.rank = "SSS";
        } else if (score > 95000) {
          $scope.rank = "SS";
        } else if (score > 92500) {
          $scope.rank = "S";
        } else if (score > 90000) {
          $scope.rank = "A";
        } else if (score > 80000) {
          $scope.rank = "B";
        } else if (score > 70000) {
          $scope.rank = "C";
        } else {
          $scope.rank = "D";
        }
        if ($scope.rank === "D") {
          return $scope.result = "Failed";
        } else {
          if ($scope.score >= 100000) {
            $scope.result = "Perfect!!";
          } else {
            $scope.result = "Clear!";
          }
          return $scope.tweet = "http://twitter.com/?status=" + g_music[_gameId].title + " " + $scope.result + " score " + $scope.score + " rank " + $scope.rank;
        }
      });
    };
    _gameId = $routeParams.id;
    if (_game == null) {
      _game = new Game();
    }
    return _game.start(g_music[$routeParams.id], _loadCallback, _endCallback);
  });

  flavaApp.controller('SelectCtrl', function($scope) {
    var i, level, value, _i, _j, _len, _ref;
    $scope.desc = false;
    $scope.music = g_music;
    _ref = $scope.music;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      value = _ref[_i];
      level = 'Level ';
      for (i = _j = 0; _j <= 9; i = ++_j) {
        if (i < value.level) {
          level += '<i class="fa fa-star-o level"></i>';
        }
      }
      value.levelIcon = level;
    }
    return $scope.changeSort = function() {
      return $scope.desc = !$scope.desc;
    };
  });

  flavaApp.controller('GameInfoCtrl', function($scope) {
    var i, level, _i;
    $scope.music = g_music[_gameId];
    level = 'Level ';
    for (i = _i = 0; _i <= 9; i = ++_i) {
      if (i < $scope.music.level) {
        level += '<i class="fa fa-star-o level"></i>';
      }
    }
    return $scope.music.levelIcon = level;
  });

}).call(this);
