// Generated by CoffeeScript 1.8.0
(function() {
  this.Game = (function() {
    var _endTime, _fallDist, _game, _generateNote, _getSprite, _music, _note, _noteHeight, _noteWidth, _pool, _poolSprite, _renderLogo, _score, _status, _threshold;

    _fallDist = 550;

    _noteWidth = 64;

    _noteHeight = 64;

    _endTime = 90;

    _threshold = {
      great: 0.1,
      good: 0.2
    };

    _game = null;

    _note = {
      index: 0,
      group: null,
      timing: [],
      key: [],
      speed: 0
    };

    _music = null;

    _status = "stop";

    _pool = {
      note: []
    };

    _score = {
      board: null,
      actual: 0,
      shown: 0
    };

    function Game(parms) {
      enchant();
      _game = new Core(980, 600);
      _game.fps = 36;
      _game.preload("img/chara1.png", "img/chara1_shadow.png", "img/logo.png", "img/score.png");
      _note.group = new Group();
      _note.index = 0;
    }

    Game.prototype.play = function(music) {
      console.log(music.src);
      _game.preload(music.src, music.img);
      _endTime = music.endTime;
      _note.timing = music.note.timing;
      _note.key = music.note.key;
      _note.speed = music.note.speed;
      _game.start();
      return _game.onload = function() {
        var i, note, noteShadow, v, _i, _j, _len, _ref;
        _music = _game.assets[music.src];
        for (i = _i = 0; _i < 5; i = ++_i) {
          noteShadow = new Sprite(_noteWidth, _noteHeight);
          noteShadow.y = -_noteHeight + _fallDist;
          noteShadow.opacity = 0.6;
          noteShadow.x = i * (_noteWidth + 20) + 480;
          noteShadow.image = _game.assets["img/chara1_shadow.png"];
          _game.rootScene.addChild(noteShadow);
        }
        _renderLogo();
        _score.board = new Score({
          game: _game,
          offsetX: 20,
          offsetY: 360,
          url: "img/score.png",
          num: 6,
          width: 36,
          height: 49.7
        });
        _score.board.generate();
        _score.board.update(0);
        _game.rootScene.addChild(_note.group);
        _ref = _note.timing;
        for (i = _j = 0, _len = _ref.length; _j < _len; i = ++_j) {
          v = _ref[i];
          note = new Sprite(_noteWidth, _noteHeight);
          note.image = _game.assets["img/chara1.png"];
          _poolSprite(_pool.note, note);
        }
        return _game.rootScene.addEventListener("enterframe", function() {
          music = _music;
          note = _note;
          if (_status === "playing") {
            if (note.timing[note.index] != null) {
              if (music.currentTime > (note.timing[note.index] - (_fallDist / note.speed)) - (1 / _game.fps)) {
                _generateNote(note.index++);
              }
            }
            if (_score.actual > _score.shown) {
              _score.shown += 100000 / _note.timing.length / 6;
              if (_score.actual < _score.shown) {
                _score.shown = _score.actual;
              }
              _score.board.update(Math.ceil(_score.shown));
            }
          }
          if (music.currentTime >= _endTime || music.duration <= music.currentTime) {
            if (music.volume - 0.1 < 0) {
              music.volume = 0;
            } else {
              music.volume -= 0.1;
            }
            if (music.volume <= 0) {
              music.stop();
              music.volume = 1;
              music.currentTime = 0;
              return _status = "stop";
            }
          }
        });
      };
    };

    _renderLogo = function() {
      var logo;
      logo = new Sprite(200, 50);
      logo.image = _game.assets["img/logo.png"];
      logo.y = 40;
      logo.x = 10;
      return _game.rootScene.addChild(logo);
    };

    _generateNote = function(number) {
      var note;
      note = _getSprite(_pool.note);
      note.number = number;
      note.key = _note.key[number];
      note.destinationY = -_noteHeight + _fallDist;
      note.y = -_noteHeight;
      note.x = note.key * (note.width + 20) + 480;
      note.frame = 0;
      note.timing = _note.timing[number];
      note.clear = false;
      note.opacity = 1;
      note.tl.clear();
      note.tl.setTimeBased();
      note.tl.scaleTo(1, 1, 0);
      note.tl.moveY(note.destinationY, (_fallDist / _note.speed) * 1000);
      note.hasClearAnimationStarted = false;
      _note.group.addChild(note);
      return note.addEventListener("enterframe", function() {
        var judge, judgeLabel, music, _ref, _ref1;
        music = _music;
        note = _note;
        if (this.oldtime != null) {
          this.rotate((music.currentTime - this.oldtime) * 500);
        }
        this.oldtime = music.currentTime;
        if (note.timing[this.number] - music.currentTime < -1) {
          this.tl.fadeOut(300).then(function() {
            return note.group.removeChild(this);
          });
        }
        if (this.clear && !this.hasClearAnimationStarted) {
          this.tl.clear();
          this.tl.scaleTo(1.5, 1.5, 200).and().fadeOut(200).then(function() {
            return note.group.removeChild(this);
          });
          if ((-_threshold.great < (_ref = note.timing[this.number] - this.clearTime) && _ref < _threshold.great)) {
            judge = "great";
            _game.score.actual += 100000 / _note.timing.length;
          } else if ((-_threshold.good < (_ref1 = note.timing[this.number] - this.clearTime) && _ref1 < _threshold.good)) {
            judge = "good";
            _game.score.actual += 70000 / _note.timing.length;
          } else {
            judge = "bad";
          }
          judgeLabel = new Label(judge);
          judgeLabel.x = 450;
          judgeLabel.y = 450;
          _game.rootScene.addChild(judgeLabel);
          judgeLabel.tl.setTimeBased();
          judgeLabel.tl.fadeOut(300).and().moveY(400, 300).then(function() {
            return _game.rootScene.removeChild(judgeLabel);
          });
          return this.hasClearAnimationStarted = true;
        }
      });
    };

    _poolSprite = function(pool, sprite) {
      pool.push(sprite);
      sprite.active = false;
      if (sprite.addEventListener) {
        return sprite.addEventListener("removed", function() {
          return this.active = false;
        });
      }
    };

    _getSprite = function(pool) {
      var i, value, _i, _len;
      for (i = _i = 0, _len = pool.length; _i < _len; i = ++_i) {
        value = pool[i];
        if (!value.active) {
          value.active = true;
          return value;
        }
      }
      console.log("error sprite pool empty");
      return false;
    };

    document.addEventListener("keydown", function(e) {
      var code, music, value, _i, _len, _ref, _ref1, _results;
      music = _music;
      if (_status === "stop") {
        if (e.keyCode === 13) {
          music.play();
          return _status = "playing";
        }
      } else if (_status = "playing") {
        _ref = _note.group.childNodes;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          value = _ref[_i];
          switch (e.keyCode) {
            case 90:
              code = 0;
              break;
            case 83:
              code = 1;
              break;
            case 88:
              code = 2;
              break;
            case 68:
              code = 3;
              break;
            case 67:
              code = 4;
              break;
            default:
              code = null;
          }
          if (value.key === code) {
            if ((-1 < (_ref1 = value.timing - music.currentTime) && _ref1 < 1)) {
              value.clear = true;
              value.clearTime = music.currentTime;
              break;
            } else {
              _results.push(void 0);
            }
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    });

    return Game;

  })();

}).call(this);
