// Generated by CoffeeScript 1.8.0
(function() {
  this.g_music = [
    {
      id: 0,
      title: 'ouroboros',
      level: 3,
      by: "2Melo",
      license: "Licensed under Creative Commons By Attribution-NonCommercial 3.0",
      img: "music/ouroboros.jpg",
      src: "music/Ouroboros.mp3",
      endTime: 170,
      note: {
        timing: [],
        key: [],
        speed: 800
      }
    }, {
      id: 1,
      title: 'test',
      level: 4,
      by: "2Melo",
      license: "Licensed under Creative Commons By Attribution-NonCommercial 3.0",
      img: "music/ouroboros.jpg",
      src: "music/Ouroboros.mp3",
      endTime: 90,
      note: {
        timing: [2.317, 4.521, 6.759, 8.982, 11.269, 13.500, 15.731, 18.002, 20.242, 22.448, 24.753, 26.960, 29.180, 31.455, 33.730, 35.899, 38.170, 40.377, 42.665, 44.886, 47.127, 49.354, 51.654, 53.825, 56.081, 58.306, 60.544, 62.781, 65.039, 67.278, 69.498, 71.773, 74.010, 76.216, 80.793, 83.015, 85.224, 89.752, 92.022, 94.294],
        key: [0, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1, 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1],
        speed: 500
      }
    }
  ];

}).call(this);
