// Generated by CoffeeScript 1.8.0
(function() {
  var k, v;

  this.g_res = {
    note: "img/chara1.png",
    noteDist: "img/chara1_shadow.png",
    score: "img/score.png"
  };

  this.g_resouces = [];

  for (k in g_res) {
    v = g_res[k];
    this.g_resouces.push(v);
  }

}).call(this);
