// Generated by CoffeeScript 1.6.3
(function() {
  window.Score = (function() {
    var _group;

    _group = null;

    function Score(parms) {
      var name, value;
      for (name in parms) {
        value = parms[name];
        this[name] = value;
        console.log(value);
      }
    }

    Score.prototype.generate = function() {
      var i, score;
      i = 0;
      _group = new Group();
      while (i < this.num) {
        score = new Sprite(this.width, this.height);
        score.image = this.game.assets[this.url];
        score.frame = i;
        score.x = this.offsetX + score.width * i;
        score.y = this.offsetY;
        _group.addChild(score);
        i++;
      }
      return this.game.rootScene.addChild(_group);
    };

    Score.prototype.update = function(score) {
      var base, value, _i, _len, _ref, _results;
      base = Math.pow(10, this.num - 1);
      _ref = _group.childNodes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        value = _ref[_i];
        value.frame = ~~(score / base);
        score = score % base;
        _results.push(base = base / 10);
      }
      return _results;
    };

    return Score;

  })();

}).call(this);
